# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowSums_c <- function(x) {
    .Call('_rENA_rowSums_c', PACKAGE = 'rENA', x)
}

c_cor <- function(mat) {
    .Call('_rENA_c_cor', PACKAGE = 'rENA', mat)
}

sphere_norm_c <- function(dfM) {
    .Call('_rENA_sphere_norm_c', PACKAGE = 'rENA', dfM)
}

dont_sphere_norm_c <- function(dfM) {
    .Call('_rENA_dont_sphere_norm_c', PACKAGE = 'rENA', dfM)
}

pca_c <- function(m, dims = 2L) {
    .Call('_rENA_pca_c', PACKAGE = 'rENA', m, dims)
}

center_data_c <- function(values) {
    .Call('_rENA_center_data_c', PACKAGE = 'rENA', values)
}

triIndices <- function(len, row = 0L) {
    .Call('_rENA_triIndices', PACKAGE = 'rENA', len, row)
}

getcor <- function(dists, normed, x, NtriOne, NtriTwo, KtriOne, KtriTwo, dim = 0L) {
    .Call('_rENA_getcor', PACKAGE = 'rENA', dists, normed, x, NtriOne, NtriTwo, KtriOne, KtriTwo, dim)
}

getN <- function(normed) {
    .Call('_rENA_getN', PACKAGE = 'rENA', normed)
}

getK <- function(normed) {
    .Call('_rENA_getK', PACKAGE = 'rENA', normed)
}

getRotationDistances_c <- function(rotated) {
    .Call('_rENA_getRotationDistances_c', PACKAGE = 'rENA', rotated)
}

get_optimized_node_pos_c <- function(normedFiltered, opted, num_dims = 2L, num_samples = 3L, max_iter = 1000L, return_all = TRUE) {
    .Call('_rENA_get_optimized_node_pos_c', PACKAGE = 'rENA', normedFiltered, opted, num_dims, num_samples, max_iter, return_all)
}

lm_ <- function(x) {
    .Call('_rENA_lm_', PACKAGE = 'rENA', x)
}

full_opt_c <- function(normed, rotated, optim_nodes, dims = 2L, num_samples = 3L, checkUnique = FALSE) {
    .Call('_rENA_full_opt_c', PACKAGE = 'rENA', normed, rotated, optim_nodes, dims, num_samples, checkUnique)
}

calc_cor <- function(x, set, dim) {
    .Call('_rENA_calc_cor', PACKAGE = 'rENA', x, set, dim)
}

soln_MPS <- function(x) {
    .Call('_rENA_soln_MPS', PACKAGE = 'rENA', x)
}

soln_calc_c <- function(coeff, xi, ti, w, dim) {
    .Call('_rENA_soln_calc_c', PACKAGE = 'rENA', coeff, xi, ti, w, dim)
}

remove_zero_rows_c <- function(toFilter) {
    .Call('_rENA_remove_zero_rows_c', PACKAGE = 'rENA', toFilter)
}

remove_zero_rows_by_c <- function(toFilter, indices) {
    .Call('_rENA_remove_zero_rows_by_c', PACKAGE = 'rENA', toFilter, indices)
}

linderoth_pos_es <- function(adjMats, t, numDims) {
    .Call('_rENA_linderoth_pos_es', PACKAGE = 'rENA', adjMats, t, numDims)
}

merge_columns_c <- function(df, cols, sep = ".") {
    .Call('_rENA_merge_columns_c', PACKAGE = 'rENA', df, cols, sep)
}

rows_to_co_occurrences <- function(df, binary = TRUE) {
    .Call('_rENA_rows_to_co_occurrences', PACKAGE = 'rENA', df, binary)
}

ref_window_df <- function(df, windowSize = 1, windowForward = 0, binary = TRUE, binaryStanzas = FALSE) {
    .Call('_rENA_ref_window_df', PACKAGE = 'rENA', df, windowSize, windowForward, binary, binaryStanzas)
}

ref_window_lag <- function(df, windowSize = 0L, binary = TRUE) {
    .Call('_rENA_ref_window_lag', PACKAGE = 'rENA', df, windowSize, binary)
}

ref_window_sum <- function(df, binary = TRUE) {
    .Call('_rENA_ref_window_sum', PACKAGE = 'rENA', df, binary)
}

svector_to_ut <- function(v) {
    .Call('_rENA_svector_to_ut', PACKAGE = 'rENA', v)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_rENA_RcppExport_registerCCallable', PACKAGE = 'rENA')
})
